name: Update Data Source

on:
  schedule:
    - cron: '0 0 1 1 *' # Runs annually on January 1st at midnight

jobs:
  update-datasource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
